class Surah {
  final int id;
  final int number;
  final String nameAr;
  final int totalAyahs;

  const Surah({
    required this.id,
    required this.number,
    required this.nameAr,
    required this.totalAyahs,
  });

  factory Surah.fromJson(Map<String, dynamic> json) {
    return Surah(
      id: json['id'] ?? 0,
      number: json['number'] ?? 0,
      nameAr: json['name_ar'] ?? '',
      totalAyahs: json['total_ayahs'] ?? 0,
    );
  }
}

const List<Surah> surahs = [
  Surah(id: 1, number: 1, nameAr: 'الفاتحة', totalAyahs: 7),
  Surah(id: 2, number: 2, nameAr: 'البقرة', totalAyahs: 286),
  Surah(id: 3, number: 3, nameAr: 'آل عمران', totalAyahs: 200),
  Surah(id: 4, number: 4, nameAr: 'النساء', totalAyahs: 176),
  Surah(id: 5, number: 5, nameAr: 'المائدة', totalAyahs: 120),
  Surah(id: 6, number: 6, nameAr: 'الأنعام', totalAyahs: 165),
  Surah(id: 7, number: 7, nameAr: 'الأعراف', totalAyahs: 206),
  Surah(id: 8, number: 8, nameAr: 'الأنفال', totalAyahs: 75),
  Surah(id: 9, number: 9, nameAr: 'التوبة', totalAyahs: 129),
  Surah(id: 10, number: 10, nameAr: 'يونس', totalAyahs: 109),
  Surah(id: 11, number: 11, nameAr: 'هود', totalAyahs: 123),
  Surah(id: 12, number: 12, nameAr: 'يوسف', totalAyahs: 111),
  Surah(id: 13, number: 13, nameAr: 'الرعد', totalAyahs: 43),
  Surah(id: 14, number: 14, nameAr: 'إبراهيم', totalAyahs: 52),
  Surah(id: 15, number: 15, nameAr: 'الحجر', totalAyahs: 99),
  Surah(id: 16, number: 16, nameAr: 'النحل', totalAyahs: 128),
  Surah(id: 17, number: 17, nameAr: 'الإسراء', totalAyahs: 111),
  Surah(id: 18, number: 18, nameAr: 'الكهف', totalAyahs: 110),
  Surah(id: 19, number: 19, nameAr: 'مريم', totalAyahs: 98),
  Surah(id: 20, number: 20, nameAr: 'طه', totalAyahs: 135),
  Surah(id: 21, number: 21, nameAr: 'الأنبياء', totalAyahs: 112),
  Surah(id: 22, number: 22, nameAr: 'الحج', totalAyahs: 78),
  Surah(id: 23, number: 23, nameAr: 'المؤمنون', totalAyahs: 118),
  Surah(id: 24, number: 24, nameAr: 'النور', totalAyahs: 64),
  Surah(id: 25, number: 25, nameAr: 'الفرقان', totalAyahs: 77),
  Surah(id: 26, number: 26, nameAr: 'الشعراء', totalAyahs: 227),
  Surah(id: 27, number: 27, nameAr: 'النمل', totalAyahs: 93),
  Surah(id: 28, number: 28, nameAr: 'القصص', totalAyahs: 88),
  Surah(id: 29, number: 29, nameAr: 'العنكبوت', totalAyahs: 69),
  Surah(id: 30, number: 30, nameAr: 'الروم', totalAyahs: 60),
  Surah(id: 31, number: 31, nameAr: 'لقمان', totalAyahs: 34),
  Surah(id: 32, number: 32, nameAr: 'السجدة', totalAyahs: 30),
  Surah(id: 33, number: 33, nameAr: 'الأحزاب', totalAyahs: 73),
  Surah(id: 34, number: 34, nameAr: 'سبأ', totalAyahs: 54),
  Surah(id: 35, number: 35, nameAr: 'فاطر', totalAyahs: 45),
  Surah(id: 36, number: 36, nameAr: 'يس', totalAyahs: 83),
  Surah(id: 37, number: 37, nameAr: 'الصافات', totalAyahs: 182),
  Surah(id: 38, number: 38, nameAr: 'ص', totalAyahs: 88),
  Surah(id: 39, number: 39, nameAr: 'الزمر', totalAyahs: 75),
  Surah(id: 40, number: 40, nameAr: 'غافر', totalAyahs: 85),
  Surah(id: 41, number: 41, nameAr: 'فصلت', totalAyahs: 54),
  Surah(id: 42, number: 42, nameAr: 'الشورى', totalAyahs: 53),
  Surah(id: 43, number: 43, nameAr: 'الزخرف', totalAyahs: 89),
  Surah(id: 44, number: 44, nameAr: 'الدخان', totalAyahs: 59),
  Surah(id: 45, number: 45, nameAr: 'الجاثية', totalAyahs: 37),
  Surah(id: 46, number: 46, nameAr: 'الأحقاف', totalAyahs: 35),
  Surah(id: 47, number: 47, nameAr: 'محمد', totalAyahs: 38),
  Surah(id: 48, number: 48, nameAr: 'الفتح', totalAyahs: 29),
  Surah(id: 49, number: 49, nameAr: 'الحجرات', totalAyahs: 18),
  Surah(id: 50, number: 50, nameAr: 'ق', totalAyahs: 45),
  Surah(id: 51, number: 51, nameAr: 'الذاريات', totalAyahs: 60),
  Surah(id: 52, number: 52, nameAr: 'الطور', totalAyahs: 49),
  Surah(id: 53, number: 53, nameAr: 'النجم', totalAyahs: 62),
  Surah(id: 54, number: 54, nameAr: 'القمر', totalAyahs: 55),
  Surah(id: 55, number: 55, nameAr: 'الرحمن', totalAyahs: 78),
  Surah(id: 56, number: 56, nameAr: 'الواقعة', totalAyahs: 96),
  Surah(id: 57, number: 57, nameAr: 'الحديد', totalAyahs: 29),
  Surah(id: 58, number: 58, nameAr: 'المجادلة', totalAyahs: 22),
  Surah(id: 59, number: 59, nameAr: 'الحشر', totalAyahs: 24),
  Surah(id: 60, number: 60, nameAr: 'الممتحنة', totalAyahs: 13),
  Surah(id: 61, number: 61, nameAr: 'الصف', totalAyahs: 14),
  Surah(id: 62, number: 62, nameAr: 'الجمعة', totalAyahs: 11),
  Surah(id: 63, number: 63, nameAr: 'المنافقون', totalAyahs: 11),
  Surah(id: 64, number: 64, nameAr: 'التغابن', totalAyahs: 18),
  Surah(id: 65, number: 65, nameAr: 'الطلاق', totalAyahs: 12),
  Surah(id: 66, number: 66, nameAr: 'التحريم', totalAyahs: 12),
  Surah(id: 67, number: 67, nameAr: 'الملك', totalAyahs: 30),
  Surah(id: 68, number: 68, nameAr: 'القلم', totalAyahs: 52),
  Surah(id: 69, number: 69, nameAr: 'الحاقة', totalAyahs: 52),
  Surah(id: 70, number: 70, nameAr: 'المعارج', totalAyahs: 44),
  Surah(id: 71, number: 71, nameAr: 'نوح', totalAyahs: 28),
  Surah(id: 72, number: 72, nameAr: 'الجن', totalAyahs: 28),
  Surah(id: 73, number: 73, nameAr: 'المزمل', totalAyahs: 20),
  Surah(id: 74, number: 74, nameAr: 'المدثر', totalAyahs: 56),
  Surah(id: 75, number: 75, nameAr: 'القيامة', totalAyahs: 40),
  Surah(id: 76, number: 76, nameAr: 'الإنسان', totalAyahs: 31),
  Surah(id: 77, number: 77, nameAr: 'المرسلات', totalAyahs: 50),
  Surah(id: 78, number: 78, nameAr: 'النبأ', totalAyahs: 40),
  Surah(id: 79, number: 79, nameAr: 'النازعات', totalAyahs: 46),
  Surah(id: 80, number: 80, nameAr: 'عبس', totalAyahs: 42),
  Surah(id: 81, number: 81, nameAr: 'التكوير', totalAyahs: 29),
  Surah(id: 82, number: 82, nameAr: 'الإنفطار', totalAyahs: 19),
  Surah(id: 83, number: 83, nameAr: 'المطففين', totalAyahs: 36),
  Surah(id: 84, number: 84, nameAr: 'الإنشقاق', totalAyahs: 25),
  Surah(id: 85, number: 85, nameAr: 'البروج', totalAyahs: 22),
  Surah(id: 86, number: 86, nameAr: 'الطارق', totalAyahs: 17),
  Surah(id: 87, number: 87, nameAr: 'الأعلى', totalAyahs: 19),
  Surah(id: 88, number: 88, nameAr: 'الغاشية', totalAyahs: 26),
  Surah(id: 89, number: 89, nameAr: 'الفجر', totalAyahs: 30),
  Surah(id: 90, number: 90, nameAr: 'البلد', totalAyahs: 20),
  Surah(id: 91, number: 91, nameAr: 'الشمس', totalAyahs: 15),
  Surah(id: 92, number: 92, nameAr: 'الليل', totalAyahs: 21),
  Surah(id: 93, number: 93, nameAr: 'الضحى', totalAyahs: 11),
  Surah(id: 94, number: 94, nameAr: 'الشرح', totalAyahs: 8),
  Surah(id: 95, number: 95, nameAr: 'التين', totalAyahs: 8),
  Surah(id: 96, number: 96, nameAr: 'العلق', totalAyahs: 19),
  Surah(id: 97, number: 97, nameAr: 'القدر', totalAyahs: 5),
  Surah(id: 98, number: 98, nameAr: 'البينة', totalAyahs: 8),
  Surah(id: 99, number: 99, nameAr: 'الزلزلة', totalAyahs: 8),
  Surah(id: 100, number: 100, nameAr: 'العاديات', totalAyahs: 11),
  Surah(id: 101, number: 101, nameAr: 'القارعة', totalAyahs: 11),
  Surah(id: 102, number: 102, nameAr: 'التكاثر', totalAyahs: 8),
  Surah(id: 103, number: 103, nameAr: 'العصر', totalAyahs: 3),
  Surah(id: 104, number: 104, nameAr: 'الهمزة', totalAyahs: 9),
  Surah(id: 105, number: 105, nameAr: 'الفيل', totalAyahs: 5),
  Surah(id: 106, number: 106, nameAr: 'قريش', totalAyahs: 4),
  Surah(id: 107, number: 107, nameAr: 'الماعون', totalAyahs: 7),
  Surah(id: 108, number: 108, nameAr: 'الكوثر', totalAyahs: 3),
  Surah(id: 109, number: 109, nameAr: 'الكافرون', totalAyahs: 6),
  Surah(id: 110, number: 110, nameAr: 'النصر', totalAyahs: 3),
  Surah(id: 111, number: 111, nameAr: 'المسد', totalAyahs: 5),
  Surah(id: 112, number: 112, nameAr: 'الإخلاص', totalAyahs: 4),
  Surah(id: 113, number: 113, nameAr: 'الفلق', totalAyahs: 5),
  Surah(id: 114, number: 114, nameAr: 'الناس', totalAyahs: 6),
];
